### ISSUE TITLE
Small Changes Not Compiled

### ISSUE THREAD

**Issue by 58bits** [carlosl/gulp-nunjucks-render#47]
Sorry - re-opening this, as it's not the IDE. I just tried editing and compiling the parent template in Vim and the same problem occurs.

---
Have a weird problem with nunjucks. When I make small changes to a comment section in a parent template, the 'page' template that extends the parent, does not get compiled (although the file to be compiled is being passed to nunjucks). If I type an extra word or two in the source parent template, all works as expected. I suspect this is a nunjucks problem, and not gulp-nunjucks-render - but thought I'd post here as well just in case I'm missing something obvious.

Here's the issue I've posted with nunjucks... https://github.com/mozilla/nunjucks/issues/811

**Comment by 58bits** [comment]
It appears to be a problem with Gulp (Gulp 4 in this case). The timestamp of the output file is not being updated - in fact, the timestamp is being set 'back' in time 0_0.

**Comment by kamlekar** [comment]
As I had already commented: https://github.com/carlosl/gulp-nunjucks-render/issues/46#issuecomment-240906591

Same issue happened with me as well which I fixed by commenting source maps code in gulp file. Though, I am not sure whether you are using sourcemaps or not.

**Comment by 58bits** [comment]
Okay I think I've found the problem. The timestamp is not being updated, because the page template has not been changed, only the parent template - and you are reusing the page file object here `file.contents = new Buffer(result);`

**Comment by 58bits** [comment]
Here's the complete task, showing how in Gulp 4 - we can use the 'since' option to ignore pages that have not been updated. This takes care of any templates that should be ignored, because there have been no changes, however, it doesn't solve the parent template problem, which should force a complete re-compile and re-render, with new timestamps for all child templates.

Of course Git and the IDE will detect larger changes based on file size, but smaller changes in a parent template (less than a block size for the file on disk) will go undetected.

```
gulp.task('compile', function () {
  return gulp.src('./app/views/pages/**/*.+(html|njk)', {since: gulp.lastRun('compile') })
    .pipe(data(function () {
      return {
        bust: loadRevisionManifest('./app/data/rev-manifest.json'),
        timestamp: `Infonomic.io compiled at ${new Date().toISOString()} ${uuid.v4()}`
      }
    }))
    .pipe(nunjucks({
      path: ['./app/views/templates'],
      manageEnv: nunjucksEnvironment
    }))
    .pipe(gulp.dest('./public'))
});
```

**Comment by 58bits** [comment]
Here's the related Gulp issues, although not sure what the outcome is here... https://github.com/gulpjs/gulp/issues/1461

**Comment by 58bits** [comment]
Here's my interim solution.... using gulp-shell.

```
var data = require('gulp-data');
var nunjucks = require('gulp-nunjucks-render');
var shell = require('gulp-shell');

gulp.task('compile', function () {
  return gulp.src('./app/views/pages/**/*.+(html|njk)')
    .pipe(data(function () {
      return {
        bust: loadRevisionManifest('./app/data/rev-manifest.json'),
        timestamp: `Infonomic.io compiled at ${new Date().toISOString()}`
      }
    }))
    .pipe(nunjucks({
      path: ['./app/views/templates'],
      manageEnv: nunjucksEnvironment
    }))
    .pipe(gulp.dest('./public'))
    .pipe(shell([
      'touch <%= file.path %>',
    ]))
});
```

**Comment by lf87** [comment]
Are there any updates on this? I'm having a very similar, if not the exact same issue.

Detailed here: https://stackoverflow.com/questions/49233603/detect-changes-between-multiple-source-files-using-gulp
